import { DatabaseSync } from 'node:sqlite';
import type { StoreContext } from '../context';
import { readProtectionWatermarksInsideTransaction } from './follow-ups';
import { BACKUP_PHASE_SUCCESSORS, backupOperationFromRow } from '../rows';
import type { BackupOperationRow } from '../rows';
import type { BackupOperation, BackupOperationPhase, SuccessfulBackupSnapshot } from '../types';
import { isCanonicalInstant } from '../../../shared/meeting-time';
import { isCanonicalUnsignedSqliteInteger, isCanonicalUuid } from '../../../shared/workspace-data-contract';
/**
 * Claims or resumes the one durable backup operation for the current merged watermark.
 * @param {object} input - Identities generated by the PROTECT coordinator for a new claim.
 * @return {BackupOperation | null} Resumable work, or null when DATA is already protected.
 */
export function claimBackupOperation(ctx: StoreContext, input: Readonly<{
    operationId: string;
    snapshotId: string;
    stagingDirectoryName: string;
    createdAt: string;
}>): BackupOperation | null {
    ctx.requireBackupMutationAllowed();
    const expectedStagingName = new RegExp(`^\\.staging-${input.operationId}-[0-9a-f]{16}$`);
    if (!isCanonicalUuid(input.operationId)
        || !isCanonicalUuid(input.snapshotId)
        || !isCanonicalInstant(input.createdAt)
        || !expectedStagingName.test(input.stagingDirectoryName)) {
        throw new TypeError('Backup operation claim is invalid');
    }

    try {
        ctx.database.exec('BEGIN IMMEDIATE');
        const active = readBackupOperationRow(ctx.database, `phase <> 'succeeded'`);
        if (active) {
            ctx.database.exec('COMMIT');
            return backupOperationFromRow(active);
        }
        const watermarks = readProtectionWatermarksInsideTransaction(ctx.database, );
        if (watermarks.backup_succeeded_through >= watermarks.backup_needed_through) {
            ctx.database.exec('COMMIT');
            return null;
        }
        const configuration = ctx.database.prepare(`
                SELECT backup_set_id
                FROM backup_configuration
                WHERE singleton = 1
            `).get() as {backup_set_id: string | null};
        if (configuration.backup_set_id === null) {
            ctx.database.exec('COMMIT');
            return null;
        }
        const sequenceStatement = ctx.database.prepare(`
                SELECT coalesce(max(backup_sequence), 0) + 1 AS next_sequence
                FROM backup_operations
                WHERE backup_set_id = ?
            `);
        sequenceStatement.setReadBigInts(true);
        const sequence = (sequenceStatement.get(configuration.backup_set_id) as {
            next_sequence: bigint;
        }).next_sequence;
        ctx.database.prepare(`
                INSERT INTO backup_operations (
                    operation_id,
                    backup_set_id,
                    backup_sequence,
                    snapshot_id,
                    target_revision,
                    actual_revision,
                    staging_directory_name,
                    created_at,
                    phase,
                    operation_version
                ) VALUES (?, ?, ?, ?, ?, NULL, ?, ?, 'queued', 0)
            `).run(
            input.operationId,
            configuration.backup_set_id,
            sequence,
            input.snapshotId,
            watermarks.backup_needed_through,
            input.stagingDirectoryName,
            input.createdAt,
        );
        const claimed = readBackupOperationRow(ctx.database, 'operation_id = ?', input.operationId);
        ctx.database.exec('COMMIT');
        return backupOperationFromRow(claimed!);
    }
    catch (error) {
        if (ctx.database.isTransaction) {
            ctx.database.exec('ROLLBACK');
        }
        throw error;
    }
}

/**
 * Reads the latest operation, including the most recently succeeded operation.
 * @return {BackupOperation | null} Latest durable operation.
 */
export function readBackupOperation(ctx: StoreContext): BackupOperation | null {
    ctx.requireOpen();
    const row = readBackupOperationRow(ctx.database, '1 = 1');
    return row ? backupOperationFromRow(row) : null;
}

/**
 * Reads the durable operation that owns one registered or in-progress snapshot identity.
 * @param {string} snapshotId - Canonical snapshot UUID.
 * @return {BackupOperation | null} Matching durable operation when registered.
 */
export function readBackupOperationForSnapshot(ctx: StoreContext, snapshotId: string): BackupOperation | null {
    ctx.requireOpen();
    if (!isCanonicalUuid(snapshotId)) {
        throw new TypeError('Snapshot identity is invalid');
    }
    const row = readBackupOperationRow(ctx.database, 'snapshot_id = ?', snapshotId);
    return row ? backupOperationFromRow(row) : null;
}

/**
 * Records the actual revision observed in the validated SQLite backup member.
 * @param {string} operationId - Claimed operation identity.
 * @param {string} actualRevision - Revision read from the checkpoint copy.
 * @return {BackupOperation} Updated durable operation.
 */
export function recordBackupCheckpoint(ctx: StoreContext, operationId: string, actualRevision: string): BackupOperation {
    ctx.requireBackupMutationAllowed();
    if (!isCanonicalUuid(operationId)
        || !isCanonicalUnsignedSqliteInteger(actualRevision)
        || actualRevision === '0') {
        throw new TypeError('Backup checkpoint facts are invalid');
    }
    return mutateBackupOperation(ctx.database, operationId, operation => {
        if (operation.phase === 'database-checkpoint'
            && operation.actual_revision === BigInt(actualRevision)) {
            return false;
        }
        if (operation.phase !== 'queued'
            || BigInt(actualRevision) < operation.target_revision) {
            throw new Error('Backup checkpoint does not match the claimed target');
        }
        ctx.database.prepare(`
                UPDATE backup_operations
                SET actual_revision = ?, phase = 'database-checkpoint',
                    operation_version = operation_version + 1
                WHERE operation_id = ?
            `).run(BigInt(actualRevision), operationId);
        return true;
    });
}

/**
 * Advances one validated filesystem phase without skipping protocol stages.
 * @param {string} operationId - Claimed operation identity.
 * @param {BackupOperationPhase} expectedPhase - Durable source phase.
 * @param {BackupOperationPhase} nextPhase - Required immediate successor.
 * @return {BackupOperation} Updated durable operation.
 */
export function advanceBackupOperation(ctx: StoreContext, 
    operationId: string,
    expectedPhase: BackupOperationPhase,
    nextPhase: BackupOperationPhase,
): BackupOperation {
    ctx.requireBackupMutationAllowed();
    if (!isCanonicalUuid(operationId) || BACKUP_PHASE_SUCCESSORS[expectedPhase] !== nextPhase) {
        throw new TypeError('Backup phase transition is invalid');
    }
    return mutateBackupOperation(ctx.database, operationId, operation => {
        if (operation.phase === nextPhase) {
            return false;
        }
        if (operation.phase !== expectedPhase) {
            throw new Error('Backup phase transition is stale');
        }
        ctx.database.prepare(`
                UPDATE backup_operations
                SET phase = ?, operation_version = operation_version + 1
                WHERE operation_id = ?
            `).run(nextPhase, operationId);
        return true;
    });
}

/**
 * Registers an immutable published snapshot and completes covered follow-ups atomically.
 * @param {object} input - Final verified snapshot facts.
 * @return {BackupOperation} Idempotently succeeded operation.
 */
export function recordBackupSuccess(ctx: StoreContext, input: Readonly<{
    operationId: string;
    actualRevision: string;
    rootDigest: string;
    succeededAt: string;
}>): BackupOperation {
    ctx.requireBackupMutationAllowed();
    if (!isCanonicalUuid(input.operationId)
        || !isCanonicalUnsignedSqliteInteger(input.actualRevision)
        || input.actualRevision === '0'
        || !/^[0-9a-f]{64}$/.test(input.rootDigest)
        || !isCanonicalInstant(input.succeededAt)) {
        throw new TypeError('Backup success facts are invalid');
    }
    try {
        ctx.database.exec('BEGIN IMMEDIATE');
        const operation = requireBackupOperationRow(ctx.database, input.operationId);
        if (operation.phase === 'succeeded') {
            const stored = readSuccessfulBackupSnapshot(ctx.database, input.operationId);
            if (stored.actualRevision !== input.actualRevision
                || stored.rootDigest !== input.rootDigest
                || stored.succeededAt !== input.succeededAt) {
                throw new Error('Backup success replay does not match immutable facts');
            }
            ctx.database.exec('COMMIT');
            return backupOperationFromRow(operation);
        }
        if (operation.phase !== 'published-pending-record'
            || operation.actual_revision !== BigInt(input.actualRevision)) {
            throw new Error('Backup success is not ready to record');
        }
        const watermarks = readProtectionWatermarksInsideTransaction(ctx.database, );
        if (operation.actual_revision > watermarks.backup_needed_through) {
            throw new Error('Backup success revision exceeds the durable watermark');
        }
        ctx.database.prepare(`
                INSERT INTO backup_snapshots (
                    snapshot_id,
                    operation_id,
                    backup_set_id,
                    backup_sequence,
                    actual_revision,
                    root_digest,
                    succeeded_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?)
            `).run(
            operation.snapshot_id,
            operation.operation_id,
            operation.backup_set_id,
            operation.backup_sequence,
            operation.actual_revision,
            input.rootDigest,
            input.succeededAt,
        );
        ctx.database.prepare(`
                UPDATE protection_watermarks
                SET backup_succeeded_through = ?
                WHERE singleton = 1
            `).run(operation.actual_revision);
        ctx.database.prepare(`
                UPDATE durable_followups
                SET state = 'completed', follow_up_version = 1
                WHERE state = 'pending' AND prerequisite_revision <= ?
            `).run(operation.actual_revision);
        ctx.database.prepare(`
                UPDATE backup_operations
                SET phase = 'succeeded', operation_version = operation_version + 1
                WHERE operation_id = ?
            `).run(operation.operation_id);
        const succeeded = requireBackupOperationRow(ctx.database, operation.operation_id);
        ctx.database.exec('COMMIT');
        return backupOperationFromRow(succeeded);
    }
    catch (error) {
        if (ctx.database.isTransaction) {
            ctx.database.exec('ROLLBACK');
        }
        throw error;
    }
}

/**
 * Lists immutable success records in BackupSequence order.
 * @return {readonly SuccessfulBackupSnapshot[]} Registered snapshot facts.
 */
export function readSuccessfulBackupSnapshots(ctx: StoreContext): readonly SuccessfulBackupSnapshot[] {
    ctx.requireOpen();
    const statement = ctx.database.prepare(`
            SELECT
                snapshot_id,
                backup_set_id,
                backup_sequence,
                actual_revision,
                root_digest,
                succeeded_at
            FROM backup_snapshots
            ORDER BY backup_sequence
        `);
    statement.setReadBigInts(true);
    const rows = statement.all() as Array<{
        snapshot_id: string;
        backup_set_id: string;
        backup_sequence: bigint;
        actual_revision: bigint;
        root_digest: string;
        succeeded_at: string;
    }>;
    return Object.freeze(rows.map(row => Object.freeze({
        snapshotId: row.snapshot_id,
        backupSetId: row.backup_set_id,
        backupSequence: row.backup_sequence.toString(),
        actualRevision: row.actual_revision.toString(),
        rootDigest: row.root_digest,
        succeededAt: row.succeeded_at,
    })));
}

/**
 * Reads one immutable success record for idempotent replay comparison.
 * @param {string} operationId - Canonical succeeded operation UUID.
 * @return {SuccessfulBackupSnapshot} Registered snapshot facts.
 */
export function readSuccessfulBackupSnapshot(database: DatabaseSync, operationId: string): SuccessfulBackupSnapshot {
    const statement = database.prepare(`
            SELECT
                snapshot_id,
                backup_set_id,
                backup_sequence,
                actual_revision,
                root_digest,
                succeeded_at
            FROM backup_snapshots
            WHERE operation_id = ?
        `);
    statement.setReadBigInts(true);
    const row = statement.get(operationId) as {
        snapshot_id: string;
        backup_set_id: string;
        backup_sequence: bigint;
        actual_revision: bigint;
        root_digest: string;
        succeeded_at: string;
    } | undefined;
    if (!row) {
        throw new Error('Succeeded backup operation has no snapshot record');
    }
    return Object.freeze({
        snapshotId: row.snapshot_id,
        backupSetId: row.backup_set_id,
        backupSequence: row.backup_sequence.toString(),
        actualRevision: row.actual_revision.toString(),
        rootDigest: row.root_digest,
        succeededAt: row.succeeded_at,
    });
}

/**
 * Reads the latest operation matching one internal fixed SQL predicate.
 * @param {string} predicate - DATA-owned SQL predicate fragment.
 * @param {...Array<string | bigint>} parameters - Bound predicate parameters.
 * @return {BackupOperationRow | undefined} Matching row when present.
 */
export function readBackupOperationRow(database: DatabaseSync, 
    predicate: string,
    ...parameters: Array<string | bigint>
): BackupOperationRow | undefined {
    const statement = database.prepare(`
            SELECT
                operation_id,
                backup_set_id,
                backup_sequence,
                snapshot_id,
                target_revision,
                actual_revision,
                staging_directory_name,
                created_at,
                phase,
                operation_version
            FROM backup_operations
            WHERE ${predicate}
            ORDER BY backup_sequence DESC
            LIMIT 1
        `);
    statement.setReadBigInts(true);
    return statement.get(...parameters) as BackupOperationRow | undefined;
}

/**
 * Requires one persisted operation identity.
 * @param {string} operationId - Canonical operation UUID.
 * @return {BackupOperationRow} Matching typed storage row.
 */
export function requireBackupOperationRow(database: DatabaseSync, operationId: string): BackupOperationRow {
    const operation = readBackupOperationRow(database, 'operation_id = ?', operationId);
    if (!operation) {
        throw new Error('Backup operation does not exist');
    }
    return operation;
}

/**
 * Applies one synchronous phase mutation inside an immediate transaction.
 * @param {string} operationId - Canonical operation UUID.
 * @param {function(BackupOperationRow): boolean} mutation - Validated row mutation.
 * @return {BackupOperation} Re-read immutable operation facts.
 */
export function mutateBackupOperation(database: DatabaseSync, 
    operationId: string,
    mutation: (operation: BackupOperationRow) => boolean,
): BackupOperation {
    try {
        database.exec('BEGIN IMMEDIATE');
        const operation = requireBackupOperationRow(database, operationId);
        mutation(operation);
        const updated = requireBackupOperationRow(database, operationId);
        database.exec('COMMIT');
        return backupOperationFromRow(updated);
    }
    catch (error) {
        if (database.isTransaction) {
            database.exec('ROLLBACK');
        }
        throw error;
    }
}
