/**
 * @file Aggregated public surface of the setup contract.
 */

export {
    type CancelMeetingOccurrenceRequest,
    type CancelRestoreSessionRequest,
    type ChangeMeetingOccurrenceRequest,
    type ChangeTaskOccurrenceRequest,
    type CompleteTaskRequest,
    type ConfigureBackupDestinationRequest,
    type ConfirmRestoreSessionRequest,
    type CreateCourseRequest,
    type CreateCourseWithMeetingRequest,
    type CreateHolidayRangeRequest,
    type CreateMeetingSeriesRequest,
    type CreateTaskRequest,
    type CreateTermRequest,
    type DataProtectionQueryRequest,
    type DeleteHolidayRangeRequest,
    type DeleteTaskOccurrenceOrSeriesRequest,
    type DeleteTaskRequest,
    type DiscardSetupDraftCheckpointRequest,
    type InitializeWorkspaceRequest,
    type MeetingOccurrenceImpactRequest,
    type MeetingSeriesQueryRequest,
    type PlanQueryRequest,
    type RestoreSessionQueryRequest,
    type RestoreTermAsCurrentRequest,
    type RestoreTermAsCurrentRequestCommand,
    type ResumeRestoreSessionRequest,
    type RollbackRestoreSessionRequest,
    type SaveSetupDraftCheckpointInput,
    type SaveSetupDraftCheckpointRequest,
    type SelectedBackupDestinationRequest,
    type SetTaskOccurrenceStatusRequest,
    type SetTaskProgressRequest,
    type SetupQueryRequest,
    type StartRestoreSessionRequest,
    type TaskOccurrenceImpactRequest,
    type TaskSeriesQueryRequest,
    type UndoTaskOccurrenceStateRequest,
    type UpdateHolidayRangeRequest,
    type UpdateTaskRequest,
    type UpdateTermEndDateRequest,
    WORKSPACE_SETUP_CHANNEL,
    WORKSPACE_SETUP_VALIDATION_REQUEST_KINDS,
    type WorkspaceCommandResult,
    type WorkspaceProcessRequest,
    type WorkspaceSetupOutcome,
    type WorkspaceSetupProblem,
    type WorkspaceSetupProblemCode,
    type WorkspaceSetupRequest,
} from './workspace-setup-contract/types';

export {
    isWorkspaceProcessRequest,
    isWorkspaceSetupOutcome,
    isWorkspaceSetupRequest,
} from './workspace-setup-contract/guards';

export {
    makeCancelMeetingOccurrenceRequest,
    makeCancelRestoreSessionRequest,
    makeChangeMeetingOccurrenceRequest,
    makeChangeTaskOccurrenceRequest,
    makeCompleteTaskRequest,
    makeConfigureBackupDestinationRequest,
    makeConfirmRestoreSessionRequest,
    makeCreateCourseRequest,
    makeCreateCourseWithMeetingRequest,
    makeCreateHolidayRangeRequest,
    makeCreateMeetingSeriesRequest,
    makeCreateTaskRequest,
    makeCreateTermRequest,
    makeDataProtectionQueryRequest,
    makeDeleteHolidayRangeRequest,
    makeDeleteTaskOccurrenceOrSeriesRequest,
    makeDeleteTaskRequest,
    makeDiscardSetupDraftCheckpointRequest,
    makeInitializeWorkspaceRequest,
    makeMeetingOccurrenceImpactRequest,
    makeMeetingSeriesQueryRequest,
    makePlanQueryRequest,
    makeRestoreSessionQueryRequest,
    makeRestoreTermAsCurrentRequest,
    makeResumeRestoreSessionRequest,
    makeRollbackRestoreSessionRequest,
    makeSaveSetupDraftCheckpointRequest,
    makeSelectedBackupDestinationRequest,
    makeSetTaskOccurrenceStatusRequest,
    makeSetTaskProgressRequest,
    makeSetupQueryRequest,
    makeStartRestoreSessionRequest,
    makeTaskOccurrenceImpactRequest,
    makeTaskSeriesQueryRequest,
    makeUndoTaskOccurrenceStateRequest,
    makeUpdateHolidayRangeRequest,
    makeUpdateTaskRequest,
    makeUpdateTermEndDateRequest,
} from './workspace-setup-contract/makers';
