/**
 * @file Aggregated public surface of the task contract.
 */

export {
    type ChangeTaskOccurrenceCommand,
    type CompleteTaskCommand,
    type CreateTaskCommand,
    type DeleteTaskCommand,
    type DeleteTaskOccurrenceOrSeriesCommand,
    type FutureTaskOccurrenceReplacement,
    type HistoricalTaskOccurrenceState,
    type OnceTaskOccurrenceProjection,
    type OnceTaskSchedule,
    type SetTaskOccurrenceStatusCommand,
    type SetTaskProgressCommand,
    type TaskCommand,
    type TaskDeadline,
    type TaskOccurrenceId,
    type TaskOccurrenceImpactDraft,
    type TaskOccurrenceImpactOccurrenceProjection,
    type TaskOccurrenceImpactProjection,
    type TaskOccurrenceOverrideKind,
    type TaskOccurrenceOverrideProjection,
    type TaskOccurrenceProjection,
    type TaskOccurrenceReplacement,
    type TaskOccurrenceStatus,
    type TaskOccurrenceWindow,
    type TaskProjection,
    type TaskSchedule,
    type TaskSegmentProjection,
    type TaskSeriesDetailProjection,
    type TaskSize,
    type TaskUndoCapability,
    type UndoTaskOccurrenceStateCommand,
    type UpdateTaskCommand,
    type WeeklyTaskOccurrenceProjection,
    type WeeklyTaskSchedule,
    changeTaskOccurrenceDigestProjection,
    completeTaskDigestProjection,
    createTaskDigestProjection,
    deleteTaskDigestProjection,
    deleteTaskOccurrenceOrSeriesDigestProjection,
    setTaskOccurrenceStatusDigestProjection,
    setTaskProgressDigestProjection,
    undoTaskOccurrenceStateDigestProjection,
    updateTaskDigestProjection,
} from './workspace-task-contract/types';

export {
    isTaskOccurrenceImpactProjection,
    isTaskOccurrenceProjection,
    isTaskOccurrenceWindow,
    isTaskProjection,
    isTaskSeriesDetailProjection,
} from './workspace-task-contract/guards';

export {
    deriveTaskOccurrenceId,
    normalizeChangeTaskOccurrenceCommand,
    normalizeCompleteTaskCommand,
    normalizeCreateTaskCommand,
    normalizeDeleteTaskCommand,
    normalizeDeleteTaskOccurrenceOrSeriesCommand,
    normalizeSetTaskOccurrenceStatusCommand,
    normalizeSetTaskProgressCommand,
    normalizeTaskOccurrenceImpactDraft,
    normalizeTaskOccurrenceWindow,
    normalizeTaskSchedule,
    normalizeUndoTaskOccurrenceStateCommand,
    normalizeUpdateTaskCommand,
} from './workspace-task-contract/makers';
