/**
 * @file Aggregated public surface of the course contract.
 */

export {
    type AcceptedChangeMeetingOccurrenceCommand,
    type AcceptedCreateCourseWithMeetingCommand,
    type CancelMeetingOccurrenceCommand,
    type ChangeMeetingOccurrenceCommand,
    type CourseColor,
    type CourseCreationFacts,
    type CourseProjection,
    type CourseTeachingRangeIntent,
    type CourseTeachingRangeProjection,
    type CreateCourseCommand,
    type CreateCourseWithMeetingCommand,
    type CreateMeetingSeriesCommand,
    type LegacyChangeMeetingOccurrenceCommand,
    type LegacyCreateCourseWithMeetingCommand,
    type LegacyCreateCourseWithMeetingCommandV2,
    MAX_MEETING_OCCURRENCE_WINDOW_DAYS,
    MAX_MEETING_OVERLAP_WARNINGS,
    type MeetingEffectiveRangeIntent,
    type MeetingEffectiveRangeProjection,
    type MeetingLocation,
    type MeetingOccurrenceId,
    type MeetingOccurrenceImpactDraft,
    type MeetingOccurrenceImpactOccurrenceProjection,
    type MeetingOccurrenceImpactProjection,
    type MeetingOccurrenceProjection,
    type MeetingOccurrenceWindow,
    type MeetingOverlapWarning,
    type MeetingRuleReplacement,
    type MeetingSegmentProjection,
    type MeetingSeriesCreationFacts,
    type MeetingSeriesDetailProjection,
    type MeetingSeriesProjection,
    type MeetingTypeCode,
    type MeetingWeekday,
    cancelMeetingOccurrenceDigestProjection,
    changeMeetingOccurrenceDigestProjection,
    createCourseDigestProjection,
    createCourseWithMeetingDigestProjection,
    createMeetingSeriesDigestProjection,
} from './workspace-course-contract/types';

export {
    isCourseProjection,
    isMeetingOccurrenceImpactProjection,
    isMeetingOccurrenceProjection,
    isMeetingOccurrenceWindow,
    isMeetingOverlapWarning,
    isMeetingSeriesDetailProjection,
} from './workspace-course-contract/guards';

export {
    deriveMeetingOccurrenceId,
    normalizeAcceptedChangeMeetingOccurrenceCommand,
    normalizeAcceptedCreateCourseWithMeetingCommand,
    normalizeCancelMeetingOccurrenceCommand,
    normalizeChangeMeetingOccurrenceCommand,
    normalizeCreateCourseCommand,
    normalizeCreateCourseWithMeetingCommand,
    normalizeCreateMeetingSeriesCommand,
    normalizeLegacyChangeMeetingOccurrenceCommand,
    normalizeLegacyCreateCourseWithMeetingCommand,
    normalizeLegacyCreateCourseWithMeetingCommandV2,
    normalizeMeetingOccurrenceImpactDraft,
    normalizeMeetingOccurrenceWindow,
} from './workspace-course-contract/makers';
